Remove obsolete link name (reported by takaxp)
agileware-jp/redmine_work_days pull request #15
Opened 2017-07-06 08:29 UTC by zh

Current PR is a fix for Issue #14 .

Redmine-3.4.x silently removed _link_to_content_update_ method from all sources. In fact even before that, the method was just a wrapper around the _link_to_ method:

```ruby
# redmine : app/helpers/application_helper.rb
def link_to_content_update(text, url_params = {}, html_options = {})
  link_to(text, url_params, html_options)
end
```

So I think the proposed by _takaxp_ changes are legit and safe to be done. Tested the result with _redmine -3.3.2_ and _redmine-3.4.0_ - working without problems.

2017-07-06 08:39 UTC, springkuma requested changes

2017-07-06 08:39 UTC, springkuma commented on app/views/gantts/3.x/show.html.erb
> +                {:params => params.merge(@gantt.params_previous)},
hash styleを`key: value`に修正お願いします。
`\xc2\xab`ってなんやろうね・・・ｗ

2017-07-06 08:41 UTC, zh commented on app/views/gantts/3.x/show.html.erb
> +                {:params => params.merge(@gantt.params_previous)},
その話でたけど古いrubyを使ってるお客さんがいるから違うbranchに直す予定。

2017-07-06 08:43 UTC, zh commented on app/views/gantts/3.x/show.html.erb
> +                {:params => params.merge(@gantt.params_previous)},
\xc2\xabは<<と>>

2017-07-06 08:46 UTC, springkuma commented on app/views/gantts/3.x/show.html.erb
> +                {:params => params.merge(@gantt.params_previous)},
1.8以前…？これまた。。了解です。

2017-07-06 08:47 UTC, springkuma approved these changes

2017-07-07 02:44 UTC, urimaro commented
Ruby >= 2.0 の対応は別途行うのでmergeしますー
Thanks @zh & @springkuma.

2017-07-07 02:45 UTC, merged